"""Add created_at to users

Revision ID: 9705e7e6859f
Revises: 30a33c74c45a
Create Date: 2024-08-22 05:04:17.609669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9705e7e6859f'
down_revision: Union[str, None] = '30a33c74c45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE users SET created_at = NOW() WHERE created_at IS NULL')
    op.alter_column('users', 'created_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
